// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  myApiSidebar: require('./docs/petstore/sidebar'),
  dbrApiSidebar: [
    {
      type: 'category',
      label: 'Get endpoints',
      items: [
        'dbrapi/get-the-last-2-rows-of-rates-data',
        'dbrapi/get-all-available-apps',
        'dbrapi/get-all-language-records',
        'dbrapi/get-language-records-by-app-page-and-lang',
        'dbrapi/get-partner-id-for-a-given-id-8-code',
        'dbrapi/get-position-data-for-a-partner',
        'dbrapi/get-position-data-variant',
        'dbrapi/get-public-data-from-json-file',
        'dbrapi/get-public-data-variant-from-json-file',
        'dbrapi/get-public-partner-data-p-variant',
        'dbrapi/get-public-partner-data-pp-variant',
        'dbrapi/get-the-latest-dbr-test-index',
        'dbrapi/get-user-data-by-partner-id',
        'dbrapi/get-va-switch-status-for-a-partner',
        'dbrapi/get-va-switch-status-variant',
        'dbrapi/get-va-vote-row',
        'dbrapi/get-voting-data',
        'dbrapi/get-voting-data-variant'
      ]
    },
    {
      type: 'category',
      label: 'Post endpoints',
      items: [
        'dbrapi/activate-an-id-8-code',
        'dbrapi/activate-an-id-8-code-with-additional-details',
        'dbrapi/activate-id-8-code-with-details-variant',
        'dbrapi/activate-id-8-code-with-partner-id-details',
        'dbrapi/store-app-language-records',
        'dbrapi/store-language-records'
      ]
    },
    {
      type: 'category',
      label: 'Update endpoints',
      items: [
        'dbrapi/update-a-vote',
        'dbrapi/update-a-vote-variant',
        'dbrapi/update-va-switch-status',
        'dbrapi/update-va-switch-status-with-vph',
        'dbrapi/update-vote-with-utc-timestamp'
      ]
    }
  ],
  dbrSidebar: [{type: 'autogenerated', dirName: 'dbr'}],
};

export default sidebars;
